/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesExternalReferenceCodeRouteImport } from './routes/templates/$externalReferenceCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesExternalReferenceCodeRoute =
  TemplatesExternalReferenceCodeRouteImport.update({
    id: '/templates/$externalReferenceCode',
    path: '/templates/$externalReferenceCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates/$externalReferenceCode': typeof TemplatesExternalReferenceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates/$externalReferenceCode': typeof TemplatesExternalReferenceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates/$externalReferenceCode': typeof TemplatesExternalReferenceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/templates/$externalReferenceCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/templates/$externalReferenceCode'
  id: '__root__' | '/' | '/templates/$externalReferenceCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesExternalReferenceCodeRoute: typeof TemplatesExternalReferenceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$externalReferenceCode': {
      id: '/templates/$externalReferenceCode'
      path: '/templates/$externalReferenceCode'
      fullPath: '/templates/$externalReferenceCode'
      preLoaderRoute: typeof TemplatesExternalReferenceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesExternalReferenceCodeRoute: TemplatesExternalReferenceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
